---
name: comment
permissions: read-all
on: [ workflow_dispatch, pull_request ]

env:
  CSV_FILE_PREFIX: https://pub-95669c22c66d453c92c62f20aa0c5b57.r2.dev
  BUCKET: github-action
  BASE: main
  JOBS: "main_again pr"

jobs:
  comment:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "# comment" >> "$GITHUB_STEP_SUMMARY"
      - name: 'comment PR'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })